/*
 * generated by Xtext 2.31.0
 */
package de.tudresden.slr.model;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TaxonomyRuntimeModule extends AbstractTaxonomyRuntimeModule {
}
