/*
 * generated by Xtext
 */
package de.tudresden.slr.model;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TaxonomyRuntimeModule extends de.tudresden.slr.model.AbstractTaxonomyRuntimeModule {

}
