/*
 * generated by Xtext 2.31.0
 */
package de.tudresden.slr.model;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TaxonomyStandaloneSetup extends TaxonomyStandaloneSetupGenerated {

	public static void doSetup() {
		new TaxonomyStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
