/**
 * generated by Xtext
 */
package de.tudresden.slr.model.validation;

import de.tudresden.slr.model.validation.AbstractTaxonomyValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class TaxonomyValidator extends AbstractTaxonomyValidator {
}
