/*
 * generated by Xtext 2.9.1
 */
package de.tudresden.slr.model.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class TaxanomyScopeProvider extends AbstractTaxanomyScopeProvider {

}
