/*
 * generated by Xtext 2.9.1
 */
package de.tudresden.slr.model.parser.antlr;

import com.google.inject.Inject;
import de.tudresden.slr.model.parser.antlr.internal.InternalTaxanomyParser;
import de.tudresden.slr.model.services.TaxanomyGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class TaxanomyParser extends AbstractAntlrParser {

	@Inject
	private TaxanomyGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTaxanomyParser createParser(XtextTokenStream stream) {
		return new InternalTaxanomyParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public TaxanomyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TaxanomyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
