/*
 * generated by Xtext 2.9.1
 */
package de.tudresden.slr.model.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class TaxanomyUiModule extends AbstractTaxanomyUiModule {
}
