/*
 * generated by Xtext 2.9.1
 */
package de.tudresden.slr.model.ui.tests;

import com.google.inject.Injector;
import de.tudresden.slr.model.taxanomy.ui.internal.TaxanomyActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class TaxanomyUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TaxanomyActivator.getInstance().getInjector("de.tudresden.slr.model.Taxanomy");
	}

}
