/**
 * generated by Xtext
 */
package de.tudresden.slr.model.taxonomy.serializer;

import de.tudresden.slr.model.taxonomy.serializer.AbstractTaxonomySemanticSequencer;

@SuppressWarnings("all")
public class TaxonomySemanticSequencer extends AbstractTaxonomySemanticSequencer {
}
