/*
 * generated by Xtext 2.9.1
 */
package de.tudresden.slr.model.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class TaxanomyProposalProvider extends AbstractTaxanomyProposalProvider {
}
