/*
 * generated by Xtext
 */
package de.tudresden.slr.model.taxonomy.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TaxonomyUiModule extends de.tudresden.slr.model.taxonomy.ui.AbstractTaxonomyUiModule {
	public TaxonomyUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
