/*
 * generated by Xtext 2.9.1
 */
package de.tudresden.slr.model


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TaxanomyRuntimeModule extends AbstractTaxanomyRuntimeModule {
}
