/*
 * generated by Xtext 2.9.1
 */
package de.tudresden.slr.model.ui;

import com.google.inject.Injector;
import de.tudresden.slr.model.taxanomy.ui.internal.TaxanomyActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TaxanomyExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TaxanomyActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TaxanomyActivator.getInstance().getInjector(TaxanomyActivator.DE_TUDRESDEN_SLR_MODEL_TAXANOMY);
	}
	
}
