/**
 *
 * $Id$
 */
package de.tudresden.slr.model.bibtex.validation;

import org.eclipse.emf.common.util.EList;

import de.tudresden.slr.model.taxonomy.Model;

/**
 * A sample validator interface for
 * {@link de.tudresden.slr.model.bibtex.Document}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DocumentValidator {
	boolean validate();

	boolean validateAuthors(EList<String> value);

	boolean validateAbstract(String value);

	boolean validateYear(String value);

	boolean validateMonth(String value);

	boolean validateTitle(String value);

	boolean validateKey(String value);

	boolean validateDoi(String value);

	boolean validateUrl(String value);

	boolean validateUnparsedAuthors(String value);

	boolean validateTaxonomy(Model value);

	boolean validateType(String value);

	boolean validateFile(String value);

	boolean validateCites(int value);
}
