/**
 * generated by Xtext 2.9.1
 */
package de.tudresden.slr.model.ui.contentassist;

import de.tudresden.slr.model.ui.contentassist.AbstractTaxanomyProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class TaxanomyProposalProvider extends AbstractTaxanomyProposalProvider {
}
