/**
 * generated by Xtext
 */
package de.tudresden.slr.model.ui.contentassist;

import de.tudresden.slr.model.ui.contentassist.AbstractTaxonomyProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class TaxonomyProposalProvider extends AbstractTaxonomyProposalProvider {
}
