/**
 * generated by Xtext
 */
package de.tudresden.slr.model.ui.contentassist;

import de.tudresden.slr.model.ui.contentassist.AbstractTaxonomyProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class TaxonomyProposalProvider extends AbstractTaxonomyProposalProvider {
}
