/**
 * generated by Xtext
 */
package de.tudresden.slr.model.taxonomy.validation;

import de.tudresden.slr.model.taxonomy.validation.AbstractTaxonomyValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TaxonomyValidator extends AbstractTaxonomyValidator {
}
