/**
 * generated by Xtext
 */
package de.tudresden.slr.model.taxonomy.serializer;

import de.tudresden.slr.model.taxonomy.serializer.AbstractTaxonomySyntacticSequencer;

@SuppressWarnings("all")
public class TaxonomySyntacticSequencer extends AbstractTaxonomySyntacticSequencer {
}
