/**
 * generated by Xtext 2.9.1
 */
package de.tudresden.slr.model.validation;

import de.tudresden.slr.model.validation.AbstractTaxanomyValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TaxanomyValidator extends AbstractTaxanomyValidator {
}
