<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="taxonomy" nsURI="http://www.tudresden.de/slr/model/Taxonomy"
    nsPrefix="de.tudresden.slr.model.taxonomy">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimensions" upperBound="-1"
        eType="#//Term" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Term">
    <eOperations name="hashCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="final int prime = 31;&#xD;&#xA;int hash = 1;&#xD;&#xA;if (eContainer instanceof Term) {&#xD;&#xA;&#x9;int parentHash = eContainer.hashCode();&#xD;&#xA;&#x9;hash = prime * hash + parentHash ^ (parentHash >> 32);&#xD;&#xA;}&#xD;&#xA;int nameHash = name.hashCode();&#xD;&#xA;hash = prime * hash + nameHash ^ (nameHash >> 32);&#xD;&#xA;return hash;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subclasses" upperBound="-1"
        eType="#//Term" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
