/**
 *
 * $Id$
 */
package de.tudresden.slr.model.taxonomy.validation;

import org.eclipse.emf.common.util.EList;

import de.tudresden.slr.model.taxonomy.Term;

/**
 * A sample validator interface for {@link de.tudresden.slr.model.taxonomy.Term}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TermValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateSubclasses(EList<Term> value);
}
