/**
 * generated by Xtext 2.9.1
 */
package de.tudresden.slr.model;

import de.tudresden.slr.model.AbstractTaxanomyRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TaxanomyRuntimeModule extends AbstractTaxanomyRuntimeModule {
}
