/**
 * generated by Xtext 2.9.1
 */
package de.tudresden.slr.model;

import de.tudresden.slr.model.TaxanomyStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TaxanomyStandaloneSetup extends TaxanomyStandaloneSetupGenerated {
  public static void doSetup() {
    TaxanomyStandaloneSetup _taxanomyStandaloneSetup = new TaxanomyStandaloneSetup();
    _taxanomyStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
