/*
 * generated by Xtext 2.31.0
 */
package de.tudresden.slr.model.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.resource.containers.IAllContainersState;
import org.eclipse.xtext.ui.editor.model.IResourceForEditorInputFactory;
import org.eclipse.xtext.ui.editor.model.ResourceForIEditorInputFactory;
import org.eclipse.xtext.ui.resource.IResourceSetProvider;
import org.eclipse.xtext.ui.resource.SimpleResourceSetProvider;

import com.google.inject.Provider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TaxonomyUiModule extends AbstractTaxonomyUiModule {

	public TaxonomyUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public Class<? extends IResourceForEditorInputFactory> bindIResourceForEditorInputFactory() {
		return ResourceForIEditorInputFactory.class;
	}
	
	@Override
	public Class<? extends IResourceSetProvider> bindIResourceSetProvider() {
	    return SimpleResourceSetProvider.class;
	}
	
    @Override
    public Provider<? extends IAllContainersState> provideIAllContainersState() {
    	return org.eclipse.xtext.ui.shared.Access.getWorkspaceProjectsState();
    }
    
}
