/*
 * generated by Xtext 2.31.0
 */
package de.tudresden.slr.model.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TaxonomyUiModule extends AbstractTaxonomyUiModule {

	public TaxonomyUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
