/*
 * generated by Xtext 2.9.1
 */
package de.tudresden.slr.model.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTaxanomyScopeProvider extends DelegatingScopeProvider {
}
