/**
 * generated by Xtext 2.9.1
 */
package de.tudresden.slr.model.ui;

import de.tudresden.slr.model.ui.AbstractTaxanomyUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TaxanomyUiModule extends AbstractTaxanomyUiModule {
  public TaxanomyUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
