/**
 * generated by Xtext 2.9.1
 */
package de.tudresden.slr.model.scoping;

import de.tudresden.slr.model.scoping.AbstractTaxanomyScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class TaxanomyScopeProvider extends AbstractTaxanomyScopeProvider {
}
