/*
 * generated by Xtext
 */
package de.tudresden.slr.model.taxonomy.ui.contentassist

import de.tudresden.slr.model.taxonomy.ui.contentassist.AbstractTaxonomyProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class TaxonomyProposalProvider extends AbstractTaxonomyProposalProvider {
}
