/*
 * generated by Xtext
 */
package de.tudresden.slr.model.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TaxonomyAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/tudresden/slr/model/parser/antlr/internal/InternalTaxonomy.tokens");
	}
}
