/**
 * generated by Xtext 2.9.1
 */
package de.tudresden.slr.model.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class TaxanomyDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
