# Workflow name
name: Release Android Client

env:
  # The name of the App
  app_name: SLR Toolkit
  GRADLE_USER_HOME: ./android-client/
  VERSION_NAME: '1.0.0-${{ github.run_number }}'

# When it will be triggered
on:
  # Triggers the workflow on push or pull request events
  push:
    branches:
      - android-client
  pull_request:
    branches:
      - android-client
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  Test_and_build:
    # Where it will run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./android-client/gradlew

      - name: Bump version
        uses: chkfung/android-version-actions@v1.2
        with:
          gradlePath: android-client/app/build.gradle
          versionCode: ${{ github.run_number }}
          versionName: ${{ env.VERSION_NAME }}

      - name: Run Unit Tests
        run: ./gradlew test
        working-directory: android-client

      - name: Run Lint
        run: ./gradlew lint
        working-directory: android-client

      - name: Upload lint reports
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.app_name }} ${{ env.VERSION_NAME }} Test-Reports
          path: android-client/app/build/reports
        if: always()

      - name: Build gradle project
        run: ./gradlew build
        working-directory: android-client

      - name: Build APK Release
        run: ./gradlew assemble
        working-directory: android-client

      - name: Upload APK Release
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.app_name }} ${{ env.VERSION_NAME }} APK
          path: android-client/app/build/outputs/apk/debug/

      #- name: Build APK Debug
      #  run: ./gradlew assembleDebug
      #  working-directory: android-client

      #- name: Upload APK Debug
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: ${{ env.app_name }} ${{ env.VERSION_NAME }} APK Debug
      #    path: android-client/app/build/outputs/apk/debug/
