# Workflow name
name: Release Android Client

env:
  # The name of the App
  app_name: SLR Toolkit
  GRADLE_USER_HOME: ./android-client/
  VERSION_NAME: '1.0.0-${{ github.run_number }}'
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
  SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

# When it will be triggered
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: ['master', 'android-client', 'android-client-2024']
    paths: ['android-client/**']
  pull_request:
    branches: ['master', 'android-client', 'android-client-2024']
    paths: ['android-client/**']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  Test_and_build:
    # Where it will run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./android-client/gradlew

      - name: Bump version
        uses: chkfung/android-version-actions@v1.2
        with:
          gradlePath: android-client/app/build.gradle
          versionCode: ${{ github.run_number }}
          versionName: ${{ env.VERSION_NAME }}

      - name: Run tests
        run: ./gradlew test
        working-directory: android-client

      - name: Run lint
        run: ./gradlew lint
        working-directory: android-client

      - name: Upload lint reports
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.app_name }} ${{ env.VERSION_NAME }} Test-Reports
          path: android-client/app/build/reports
        if: always()

      - name: Build gradle project
        run: ./gradlew build
        working-directory: android-client

      - name: Assemble APK release
        run: ./gradlew app:assembleRelease  # app:bundleRelease for AAB
        working-directory: android-client

      - name: Upload APK release
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.app_name }} ${{ env.VERSION_NAME }} APK Release
          path: android-client/app/build/outputs/apk/release/

#      - name: Assemble APK debug
#        run: ./gradlew assembleDebug
#        working-directory: android-client
#
#      - name: Upload APK debug
#        uses: actions/upload-artifact@v3
#        with:
#          name: ${{ env.app_name }} ${{ env.VERSION_NAME }} APK Debug
#          path: android-client/app/build/outputs/apk/debug/
